### ISSUE TITLE
in node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js  Module parse failed: Unexpected token (550:39)

### ISSUE THREAD

**Issue by heligonSeb** [Vuepic/vue-datepicker#218]
when loading my serve, have this error 
![image](https://user-images.githubusercontent.com/52566459/208056318-417ddb5a-3aed-4762-9824-ce37f46f8cef.png)

**Comment by ChrisMoutsos** [comment]
This problem seems specific to version 3.6.2 and 3.6.3. When I use version 3.6.1, it works fine.

**Comment by Jasenkoo** [comment]
Can you show me what props are you using?

**Comment by ChrisMoutsos** [comment]
I was using:

```
<Datepicker
    v-model="dateStart"
    :enable-time-picker="false"
    range
/>
```

**Comment by Jasenkoo** [comment]
Any additional info, like vue version, cli version, did you try reinstalling, and so on?

**Comment by AlperGuven** [comment]
I tried deleting and installing cli version, vue version, npm version and node_module and so on. I didn't get right results. Fixed when downgrading to 3.6.1. FYI

**Comment by Jasenkoo** [comment]
This will not be worked on. From `v3.6.1` `vite` is updated to `v4` , so it may have some internal bug in vite. The next version will have updated vite, so it may resolve the issue, if not, check the project config, since this is probably something with the internal project setup, as there are no problems in this [demo](https://stackblitz.com/edit/vue3-vue-cli-ndpejr?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue). Anyways, I am not officially supporting CLI, since they are recommending vite as a build tool going forward.

**Comment by CrixuAMG** [comment]
Issue is also present in Vue 3.2.*, which rules out a bug in vite. The issue is that `??` is used after building the dist version, which can be temporarily fixed by replacing it with `||`, which is of course not a viable solution.
Could you check what caused this breaking change?

**Comment by Jasenkoo** [comment]
@CrixuAMG The library requires `vue > 3.2` since prior versions were still in beta, and compiled version is not working with the previous, in order to make it work, it needs to be compiled with `vue < 3.2`.

**Comment by nermin99** [comment]
I have tried using Vue `3.2.0` and the latest patch `3.2.47` but I still get the same error
>  ERROR  Failed to compile with 12 errors12:09:57
 error  in ./node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js
Module parse failed: Unexpected token (179:168)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }, ml = (e, t) => {
|   if (!e) return 0;
>   const l = /* @__PURE__ */ new Date(), a = new Date(l.toLocaleString("en-US", { timeZone: "UTC" })), n = new Date(l.toLocaleString("en-US", { timeZone: e })), i = (t ?? n).getTimezoneOffset() / 60;
|   return (+a - +n) / (1e3 * 60 * 60) - i;
| };
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--15-3!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/RisikomarkeringList.vue?vue&type=script&lang=ts 6:0-51 15:4-17
